name: Integrity – youtube.response.js

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure manifest and target file exist
        run: |
          test -f .integrity/sha256sum.txt || { echo "::error ::.integrity/sha256sum.txt not found"; exit 1; }
          # Извлечём строку только для youtube.response.js (не помешает масштабироваться)
          grep -E '\smodules/youtube\.response\.js$' .integrity/sha256sum.txt > .integrity/target.txt || {
            echo "::error ::Entry for modules/youtube.response.js not found in .integrity/sha256sum.txt"
            exit 1
          }
          # Проверим наличие самого файла
          awk '{print $2}' .integrity/target.txt | xargs -I{} test -f {} || {
            echo "::error file=modules/youtube.response.js::Target file is missing in repo"
            exit 1
          }

      - name: Verify SHA-256
        run: |
          # sha256sum доступен в ubuntu-latest
          if sha256sum -c --status .integrity/target.txt; then
            echo "OK: SHA-256 matches."
          else
            echo "::error file=modules/youtube.response.js::SHA-256 mismatch. If you intentionally changed the file, run the 'Update integrity hash' workflow to refresh the manifest."
            exit 1
          fi
