name: Shadowrocket: refresh + purge CDN

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут
  workflow_dispatch:        # ручной запуск из UI

permissions:
  contents: write

concurrency:
  group: shadowrocket-refresh
  cancel-in-progress: true

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history for diff)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update timestamp in text files
        shell: bash
        run: |
          set -euo pipefail
          TS="$(date -u +'%Y-%m-%d_%H:%M:%S_UTC')"

          mapfile -t FILES < <(git ls-files \
            | grep -E '(^gg$|\.conf$|\.sgmodule$|\.module$|\.list$|\.txt$|\.yaml$|\.yml$)' \
            | grep -Ev '^\.github/')

          for f in "${FILES[@]}"; do
            # Пропускаем пустые/большие/нетекстовые
            if [ ! -s "$f" ] || [ $(stat -c%s "$f") -gt 2000000 ] || ! file --mime "$f" | grep -q 'text/'; then
              continue
            fi
            if grep -qE '^(#\s*)?last_update=' "$f"; then
              sed -i '1s/^\(#\s*\)\?last_update=.*/# last_update='"$TS"'/' "$f"
            else
              printf '# last_update=%s\n%s' "$TS" "$(cat "$f")" > "$f"
            fi
          done

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A

          if git diff --cached --quiet; then
            echo "NO_CHANGES=1" >> $GITHUB_ENV
            exit 0
          fi

          git commit -m "Refresh for Shadowrocket at $TS [skip ci]"
          git push
          echo "NO_CHANGES=0" >> $GITHUB_ENV

      - name: Collect changed files
        if: env.NO_CHANGES == '0'
        id: changed
        shell: bash
        run: |
          CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD | tr '\n' ' ')
          echo "files=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Purge jsDelivr cache
        if: env.NO_CHANGES == '0'
        shell: bash
        run: |
          set -euo pipefail
          for f in ${{ steps.changed.outputs.files }}; do
            if echo "$f" | grep -Eq '(^gg$|\.conf$|\.sgmodule$|\.module$|\.list$|\.txt$|\.yaml$|\.yml$)'; then
              URL="https://purge.jsdelivr.net/gh/Alexgood321/SR-ALL-FILES-PROXY@main/$f"
              echo "Purging: $URL"
              curl -fsS "$URL" || true
            fi
          done

      - name: Warm-up raw.githubusercontent
        if: env.NO_CHANGES == '0'
        shell: bash
        run: |
          set -euo pipefail
          TS=$(date +%s)
          for f in ${{ steps.changed.outputs.files }}; do
            if echo "$f" | grep -Eq '(^gg$|\.conf$|\.sgmodule$|\.module$|\.list$|\.txt$|\.yaml$|\.yml$)'; then
              URL="https://raw.githubusercontent.com/Alexgood321/SR-ALL-FILES-PROXY/main/$f?t=$TS"
              echo "HEAD $URL"
              curl -fsI "$URL" >/dev/null || true
            fi
          done
