name: Shadowrocket: refresh + purge CDN

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут
  workflow_dispatch:        # ручной запуск из Actions
  push:
    branches:
      - main
    paths:
      - 'modules/**'
      - 'rules/**'
      - 'config/**'
      - '*.conf'
      - '*.sgmodule'
      - '*.module'
      - '*.yaml'
      - '*.yml'
      - '*.txt'
      - '.github/workflows/**'
      - 'README.md'

permissions:
  contents: write

concurrency:
  group: shadowrocket-refresh
  cancel-in-progress: true

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update timestamp in text files
        id: touch_files
        shell: bash
        run: |
          set -euo pipefail
          TS="$(date -u +"%Y-%m-%d_%H:%M:%S_UTC")"
          exts="\.(conf|sgmodule|\.module|\.list|\.txt|\.yaml|\.yml)$"
          mapfile -t files < <(git ls-files | grep -E "${exts}" | grep -Ev '^\.github/')

          changed=0
          for f in "${files[@]}"; do
            # пропускаем пустые и большие файлы > 2МБ
            if [ ! -s "$f" ] || [ $(stat -c%s "$f") -gt 2000000 ]; then
              continue
            fi
            if ! file --mime "$f" | grep -q 'text/'; then
              continue
            fi

            if grep -qE '^(#\s*)?last_update=' "$f"; then
              sed -i '1s/^\(#\s*\)\?last_update=.*/# last_update='"$TS"'/' "$f"
            else
              printf '# last_update=%s\n%s' "$TS" "$(cat "$f")" > "$f"
            fi
            ((changed++))
          done

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ "$changed" -gt 0 ]; then
            git add -A
            git commit -m "Auto refresh (cache-bust) at $TS"
            git push
            echo "Changes committed."
          else
            echo "No changes to commit."
          fi
